SET LINESIZE 200;
COLUMN Name FORMAT A20;
COLUMN Course FORMAT A20;

CREATE TABLE Student (
    Roll_No NUMBER PRIMARY KEY,
    Name VARCHAR2(50),
    Course VARCHAR2(50),
    Year NUMBER
);

ALTER TABLE Student ADD Phone_Number NUMBER(10);

ALTER TABLE Student MODIFY Name VARCHAR2(100);

ALTER TABLE Student RENAME COLUMN Course TO Stream;

ALTER TABLE Student ADD CONSTRAINT chk_year CHECK (Year > 1900);

ALTER TABLE Student DROP CONSTRAINT chk_year;

ALTER TABLE Student DROP COLUMN Phone_Number;

TRUNCATE TABLE Student;

DROP TABLE Student;