CREATE TABLE test_tcl (
  id INT
);
INSERT ALL
INTO test_tcl VALUES (1)
INTO test_tcl VALUES (2)
INTO test_tcl VALUES (3)
SELECT 1 FROM DUAL;
COMMIT;
SELECT * FROM test_tcl;
SAVEPOINT savepoint1;
INSERT ALL
INTO test_tcl VALUES (4)
INTO test_tcl VALUES (5)
SELECT 1 FROM DUAL;
SELECT * FROM test_tcl;
ROLLBACK TO savepoint1;
SELECT * FROM test_tcl;
INSERT ALL
INTO test_tcl VALUES (6)
INTO test_tcl VALUES (7)
INTO test_tcl VALUES (8)
SELECT 1 FROM DUAL;
COMMIT;
SELECT * FROM test_tcl;
SAVEPOINT savepoint2;
INSERT ALL
INTO test_tcl VALUES (9)
INTO test_tcl VALUES (10)
INTO test_tcl VALUES (11)
INTO test_tcl VALUES (12)
SELECT 1 FROM DUAL;
ROLLBACK TO savepoint2;
SELECT * FROM test_tcl;